### PR TITLE
Handling promises better

### PR DESCRIPTION
**Pull request by fearphage**
Copied from the original PR: sinonjs/sinon#1128 and built on the foundation by @joelmukuthu

I'm not 100% happy with the way it turned out and I'm open to suggestions. I modeled it very closely to the way mocha.js handles the sitatuation. However, there is a big difference between mocha tests and sinon tests. In mocha, you know the moment you see the `fn`/`callback` whether the test is sync or async (based on the `fn.length > 0`). In sinon, you don't know until you're inside the test itself.

```js
function test1(stub, mock) // looks async because of fn.length
function test2(done) // looks async because of fn.length
function test3() // known synchronous
```
This made the abstraction not as clean as I had hoped.

### CODE REVIEW

**Comment by fearphage** [comment]
## Important notes/changes

This will now throw an error if you call `test` as an async function *and* return a promise. This is to handle the following confusing case:

```js
test(function(done) {
  done();

  return Promise.reject();
});
```

Also it will now override the error in a rejection if it is falsy or nonexistent:
```js
test(function() {
  return Promise.reject()
});
```
The rejection gets overridden and we reject with a `new Error` instead.

https://github.com/sinonjs/sinon-test/pull/20/files#diff-dd2e881af3311f834199c7b515cff0c7R46

**Comment by fatso83** [comment]
Conflicting files after merge ... Rebase.

**Comment by fearphage** [comment]
@fatso83 Rebased and tests are green again. Thanks.

**Comment by vellotis** [comment]
@fearphage ping? Is it ready to be merged?

**Comment by fearphage** [comment]
Yes, it is.

**Comment by fatso83** [comment]
@sinonjs/sinon-test-maintainers : how does this look, Rob and Shaun?

**Comment by fatso83** [comment]
Did you merge the wrong way, Phred? :-)

**Comment by fearphage** [comment]
No, I did not. I do not have write access in `sinon-test`... just `sinon` proper.

**Comment by fearphage** [comment]
I'll wait for someone/anyone else to review and/or merge this.

**Comment by fatso83** [comment]
Sorry for keeping you waiting, Phred. Good work as always.

**Pull request merged**
