### PR TITLE
Remove sinon.getConfig() deprecation warning

### PR DESCRIPTION
**Pull request by cbaclig**
I crawled the sinon and sinon-test repos, and it doesn't appear that there's any need to specifically call `sinon.getConfig()` from the passed-in `sinon` object, which is deprecated. 

Instead, I ported `getConfig()` over to this module to avoid the deprecation warning.

Feedback is appreciated!

### CODE REVIEW

**Comment by fatso83** [comment]
Hi, this looks great! And coincidentally it also would have avoided issues #33 and sinonjs/sinon#1169.  You might want to rebase your branch against `master`, and then this looks good to me :-) 

Thanks!

**Comment by fatso83** [comment]
Actually, I just testet this out locally and it worked fine, so I'm merging it.
 👍

**Comment by dentuzhik** [comment]
Hey guys, any plans to publish this into npm?
Just installed it, still seeing the warning.

**Comment by cbaclig** [comment]
I've been using `sinon-test` directly from github in my `package.json` since this module is still in (somewhat) active development pre 1.0.

That being said, I don't have permission to publish to `npm` and am not sure what the process is for that. @fatso83 may be better suited to answer that.

**Comment by fatso83** [comment]
Actually the core Sinon team has no interest in maintaining this, rather wanting to focus efforts on the core Sinon parts. We have handed over maintainership to @sinonjs/sinon-test-maintainers, so I am just casually checking the status of this.

**Comment by cbaclig** [comment]
@fatso83 I just updated to 1.0.0 (thanks!) but noticed that the deprecation warnings are still present. Looking at the code that was installed with an `npm install` it looks like the changes from this PR weren't included in the code pushed to npm even though the 1.0.0 tag here includes it. Any way we can republish to npm with these changes?

**Comment by fatso83** [comment]
Dropping a patch release in a jiffy ...

**Comment by fatso83** [comment]
And it's out! Thanks for notifying us of this glitch 👍

**Pull request merged**
