### PR TITLE
Purpose a work around of #75

### PR DESCRIPTION
**Pull request by zixia**

### CODE REVIEW

**Comment by fatso83** [comment]
Thank you for the PR, but the [tests are failing](https://travis-ci.org/sinonjs/sinon-test/jobs/274452132)

**Comment by zixia** [comment]
Okay, I'll try to fix those tests.

Just have a look into them, should not be very hard to make it compatible with `async` function.

**Comment by zixia** [comment]
Just passed the CI.

**Comment by fatso83** [comment]
Thanks for fixing the tests, but the reason the coverage test is failing is because you decreased coverage a bit by this addition. It is because you are not testing any of the code you added, just the old code that was already present. You now have a test for what happens if things are _not_ right, but you should (also) have one that proves that things are actually working as well :smiley: 

You can see the failing coverage [here](https://coveralls.io/builds/13253584/source?filename=lib%2Ftest.js#L54)

**Comment by zixia** [comment]
Yes. I can add unit test for this after I found any method like `referee.assert.noException()` , but it seems there's no such method name.

Will check it later.

**Comment by fatso83** [comment]
[referee](https://www.npmjs.com/package/referee) has a symmetric inverse of `assert` called `refute`. It is like `assert.not.*`

**Comment by fatso83** [comment]
Fails linting. Other than that, a unit test actually needs to test something :smile: Other than the fact you are calling a variable `test`, there is not a hint of something resembling a test here. You need to assert on _something_. How would we else know what is right/wrong if the test fails?

The 3A pattern is nice to keep in mind:

Arrange
Act
Assert

**Comment by zixia** [comment]
@fatso83 Thanks for letting me know the `refute`, it's exactly what I need.

I call the variable `test` in order to make sure that it does not throw exceptions. How ever, it's more clear after use `refute.exception`.

Now it's passed all the tests, cheers!

**Comment by fatso83** [comment]
Thank you!

**Comment by zixia** [comment]
You are welcome! 

Did we updated the npm package?

**Pull request merged**
