### PR TITLE
Fix compatibility with Sinon 3

### PR DESCRIPTION
**Pull request by fatso83**
This is a simple fix for #77, but also work that will make it work nicely once the deprecated methods from sinonjs/sinon#1515 are removed with version 4 of Sinon.

### CODE REVIEW

**Comment by fatso83** [comment]
I reference Sinon 3.1 in the source here, but it has not yet been released (tested against the most recent `master`, as well as 3.0 and 2.4.1). We can also wait until Sinon 3.1 has been released before merging this, but not much longer as it is presently unusable with Sinon 3.

**Comment by fatso83** [comment]
Sinon 3.1 has now been released, so I just restarted the (already green) build to verify that it still works (it did).

**Comment by mroderick** [comment]
👍

**Comment by fatso83** [comment]
Released as sinon-test 2.1

**Pull request merged**
