### PR TITLE
Add sinon as a peer dependency

### PR DESCRIPTION
**Pull request by fatso83**
Also updates the version number to the 2.x versions.

### CODE REVIEW

**Comment by jonnyreeves** [comment]
Peer dependencies are removed from npm 3: http://blog.npmjs.org/post/110924823920/npm-weekly-5

**Comment by mantoni** [comment]
@jonnyreeves Not removed, just the behavior changed. npm will not be downloading the dependency anymore, but it will warn if there is no match found. This is find for the purpose of this module. To make the tests pass, it needs to be also in the `devDependencies` though.

**Comment by fatso83** [comment]
@mantoni : Ah, true. Updating. 

Yeah, the behavior for peer dependencies is much more sane now, and it finally makes sense to use it.

**Comment by fatso83** [comment]
Updated. Good to merge?

**Comment by mantoni** [comment]
Yeah, that’s fine. Go ahead.

**Pull request merged**
